/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as CashRouteImport } from './routes/cash'
import { Route as DaybookRouteImport } from './routes/daybook'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as GstRouteImport } from './routes/gst'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as JournalVouchersRouteImport } from './routes/journal-vouchers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as PayeesRouteImport } from './routes/payees'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProformaRouteImport } from './routes/proforma'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BankIdRouteImport } from './routes/bank_.$id'
import { Route as ItemsIdRouteImport } from './routes/items_.$id'
import { Route as PartiesIdRouteImport } from './routes/parties_.$id'
import { Route as PayeesIdRouteImport } from './routes/payees_.$id'
import { Route as ProformaIdRouteImport } from './routes/proforma_.$id'
import { Route as PurchaseReturnIndexRouteImport } from './routes/purchase-return.index'
import { Route as PurchaseReturnIdRouteImport } from './routes/purchase-return.$id'
import { Route as PurchaseReturnNewRouteImport } from './routes/purchase-return.new'
import { Route as PurchaseIndexRouteImport } from './routes/purchase.index'
import { Route as PurchaseIdRouteImport } from './routes/purchase.$id'
import { Route as PurchaseNewRouteImport } from './routes/purchase.new'
import { Route as QuotationsIdRouteImport } from './routes/quotations_.$id'
import { Route as SaleReturnIndexRouteImport } from './routes/sale-return.index'
import { Route as SaleReturnIdRouteImport } from './routes/sale-return.$id'
import { Route as SaleReturnNewRouteImport } from './routes/sale-return.new'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as PurchaseEditIdRouteImport } from './routes/purchase.edit.$id'
import { Route as SalesEditIdRouteImport } from './routes/sales.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const DaybookRoute = DaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalVouchersRoute = JournalVouchersRouteImport.update({
  id: '/journal-vouchers',
  path: '/journal-vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PayeesRoute = PayeesRouteImport.update({
  id: '/payees',
  path: '/payees',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaRoute = ProformaRouteImport.update({
  id: '/proforma',
  path: '/proforma',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BankIdRoute = BankIdRouteImport.update({
  id: '/bank_/$id',
  path: '/bank/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items_/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/parties_/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayeesIdRoute = PayeesIdRouteImport.update({
  id: '/payees_/$id',
  path: '/payees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaIdRoute = ProformaIdRouteImport.update({
  id: '/proforma_/$id',
  path: '/proforma/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnIndexRoute = PurchaseReturnIndexRouteImport.update({
  id: '/purchase-return/',
  path: '/purchase-return/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnIdRoute = PurchaseReturnIdRouteImport.update({
  id: '/purchase-return/$id',
  path: '/purchase-return/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnNewRoute = PurchaseReturnNewRouteImport.update({
  id: '/purchase-return/new',
  path: '/purchase-return/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIndexRoute = PurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIdRoute = PurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseNewRoute = PurchaseNewRouteImport.update({
  id: '/purchase/new',
  path: '/purchase/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsIdRoute = QuotationsIdRouteImport.update({
  id: '/quotations_/$id',
  path: '/quotations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReturnIndexRoute = SaleReturnIndexRouteImport.update({
  id: '/sale-return/',
  path: '/sale-return/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReturnIdRoute = SaleReturnIdRouteImport.update({
  id: '/sale-return/$id',
  path: '/sale-return/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleReturnNewRoute = SaleReturnNewRouteImport.update({
  id: '/sale-return/new',
  path: '/sale-return/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseEditIdRoute = PurchaseEditIdRouteImport.update({
  id: '/purchase/edit/$id',
  path: '/purchase/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesEditIdRoute = SalesEditIdRouteImport.update({
  id: '/sales/edit/$id',
  path: '/sales/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/cash': typeof CashRoute
  '/daybook': typeof DaybookRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/journal-vouchers': typeof JournalVouchersRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payees': typeof PayeesRoute
  '/payments': typeof PaymentsRoute
  '/proforma': typeof ProformaRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bank/$id': typeof BankIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/parties/$id': typeof PartiesIdRoute
  '/payees/$id': typeof PayeesIdRoute
  '/proforma/$id': typeof ProformaIdRoute
  '/purchase-return/$id': typeof PurchaseReturnIdRoute
  '/purchase-return/new': typeof PurchaseReturnNewRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/purchase/new': typeof PurchaseNewRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/sale-return/$id': typeof SaleReturnIdRoute
  '/sale-return/new': typeof SaleReturnNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/purchase-return/': typeof PurchaseReturnIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/sale-return/': typeof SaleReturnIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/purchase/edit/$id': typeof PurchaseEditIdRoute
  '/sales/edit/$id': typeof SalesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/cash': typeof CashRoute
  '/daybook': typeof DaybookRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/journal-vouchers': typeof JournalVouchersRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payees': typeof PayeesRoute
  '/payments': typeof PaymentsRoute
  '/proforma': typeof ProformaRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bank/$id': typeof BankIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/parties/$id': typeof PartiesIdRoute
  '/payees/$id': typeof PayeesIdRoute
  '/proforma/$id': typeof ProformaIdRoute
  '/purchase-return/$id': typeof PurchaseReturnIdRoute
  '/purchase-return/new': typeof PurchaseReturnNewRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/purchase/new': typeof PurchaseNewRoute
  '/quotations/$id': typeof QuotationsIdRoute
  '/sale-return/$id': typeof SaleReturnIdRoute
  '/sale-return/new': typeof SaleReturnNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/purchase-return': typeof PurchaseReturnIndexRoute
  '/purchase': typeof PurchaseIndexRoute
  '/sale-return': typeof SaleReturnIndexRoute
  '/sales': typeof SalesIndexRoute
  '/purchase/edit/$id': typeof PurchaseEditIdRoute
  '/sales/edit/$id': typeof SalesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/cash': typeof CashRoute
  '/daybook': typeof DaybookRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/inventory': typeof InventoryRoute
  '/items': typeof ItemsRoute
  '/journal-vouchers': typeof JournalVouchersRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payees': typeof PayeesRoute
  '/payments': typeof PaymentsRoute
  '/proforma': typeof ProformaRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/bank_/$id': typeof BankIdRoute
  '/items_/$id': typeof ItemsIdRoute
  '/parties_/$id': typeof PartiesIdRoute
  '/payees_/$id': typeof PayeesIdRoute
  '/proforma_/$id': typeof ProformaIdRoute
  '/purchase-return/$id': typeof PurchaseReturnIdRoute
  '/purchase-return/new': typeof PurchaseReturnNewRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/purchase/new': typeof PurchaseNewRoute
  '/quotations_/$id': typeof QuotationsIdRoute
  '/sale-return/$id': typeof SaleReturnIdRoute
  '/sale-return/new': typeof SaleReturnNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/purchase-return/': typeof PurchaseReturnIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/sale-return/': typeof SaleReturnIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/purchase/edit/$id': typeof PurchaseEditIdRoute
  '/sales/edit/$id': typeof SalesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/cash'
    | '/daybook'
    | '/documents'
    | '/expenses'
    | '/gst'
    | '/inventory'
    | '/items'
    | '/journal-vouchers'
    | '/login'
    | '/parties'
    | '/payees'
    | '/payments'
    | '/proforma'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/bank/$id'
    | '/items/$id'
    | '/parties/$id'
    | '/payees/$id'
    | '/proforma/$id'
    | '/purchase-return/$id'
    | '/purchase-return/new'
    | '/purchase/$id'
    | '/purchase/new'
    | '/quotations/$id'
    | '/sale-return/$id'
    | '/sale-return/new'
    | '/sales/$id'
    | '/sales/new'
    | '/purchase-return/'
    | '/purchase/'
    | '/sale-return/'
    | '/sales/'
    | '/purchase/edit/$id'
    | '/sales/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/cash'
    | '/daybook'
    | '/documents'
    | '/expenses'
    | '/gst'
    | '/inventory'
    | '/items'
    | '/journal-vouchers'
    | '/login'
    | '/parties'
    | '/payees'
    | '/payments'
    | '/proforma'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/bank/$id'
    | '/items/$id'
    | '/parties/$id'
    | '/payees/$id'
    | '/proforma/$id'
    | '/purchase-return/$id'
    | '/purchase-return/new'
    | '/purchase/$id'
    | '/purchase/new'
    | '/quotations/$id'
    | '/sale-return/$id'
    | '/sale-return/new'
    | '/sales/$id'
    | '/sales/new'
    | '/purchase-return'
    | '/purchase'
    | '/sale-return'
    | '/sales'
    | '/purchase/edit/$id'
    | '/sales/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/cash'
    | '/daybook'
    | '/documents'
    | '/expenses'
    | '/gst'
    | '/inventory'
    | '/items'
    | '/journal-vouchers'
    | '/login'
    | '/parties'
    | '/payees'
    | '/payments'
    | '/proforma'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/bank_/$id'
    | '/items_/$id'
    | '/parties_/$id'
    | '/payees_/$id'
    | '/proforma_/$id'
    | '/purchase-return/$id'
    | '/purchase-return/new'
    | '/purchase/$id'
    | '/purchase/new'
    | '/quotations_/$id'
    | '/sale-return/$id'
    | '/sale-return/new'
    | '/sales/$id'
    | '/sales/new'
    | '/purchase-return/'
    | '/purchase/'
    | '/sale-return/'
    | '/sales/'
    | '/purchase/edit/$id'
    | '/sales/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  CashRoute: typeof CashRoute
  DaybookRoute: typeof DaybookRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  GstRoute: typeof GstRoute
  InventoryRoute: typeof InventoryRoute
  ItemsRoute: typeof ItemsRoute
  JournalVouchersRoute: typeof JournalVouchersRoute
  LoginRoute: typeof LoginRoute
  PartiesRoute: typeof PartiesRoute
  PayeesRoute: typeof PayeesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProformaRoute: typeof ProformaRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  BankIdRoute: typeof BankIdRoute
  ItemsIdRoute: typeof ItemsIdRoute
  PartiesIdRoute: typeof PartiesIdRoute
  PayeesIdRoute: typeof PayeesIdRoute
  ProformaIdRoute: typeof ProformaIdRoute
  PurchaseReturnIdRoute: typeof PurchaseReturnIdRoute
  PurchaseReturnNewRoute: typeof PurchaseReturnNewRoute
  PurchaseIdRoute: typeof PurchaseIdRoute
  PurchaseNewRoute: typeof PurchaseNewRoute
  QuotationsIdRoute: typeof QuotationsIdRoute
  SaleReturnIdRoute: typeof SaleReturnIdRoute
  SaleReturnNewRoute: typeof SaleReturnNewRoute
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  PurchaseReturnIndexRoute: typeof PurchaseReturnIndexRoute
  PurchaseIndexRoute: typeof PurchaseIndexRoute
  SaleReturnIndexRoute: typeof SaleReturnIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  PurchaseEditIdRoute: typeof PurchaseEditIdRoute
  SalesEditIdRoute: typeof SalesEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daybook': {
      id: '/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof DaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-vouchers': {
      id: '/journal-vouchers'
      path: '/journal-vouchers'
      fullPath: '/journal-vouchers'
      preLoaderRoute: typeof JournalVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payees': {
      id: '/payees'
      path: '/payees'
      fullPath: '/payees'
      preLoaderRoute: typeof PayeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma': {
      id: '/proforma'
      path: '/proforma'
      fullPath: '/proforma'
      preLoaderRoute: typeof ProformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank_/$id': {
      id: '/bank_/$id'
      path: '/bank/$id'
      fullPath: '/bank/$id'
      preLoaderRoute: typeof BankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items_/$id': {
      id: '/items_/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties_/$id': {
      id: '/parties_/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payees_/$id': {
      id: '/payees_/$id'
      path: '/payees/$id'
      fullPath: '/payees/$id'
      preLoaderRoute: typeof PayeesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma_/$id': {
      id: '/proforma_/$id'
      path: '/proforma/$id'
      fullPath: '/proforma/$id'
      preLoaderRoute: typeof ProformaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-return/': {
      id: '/purchase-return/'
      path: '/purchase-return'
      fullPath: '/purchase-return/'
      preLoaderRoute: typeof PurchaseReturnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-return/$id': {
      id: '/purchase-return/$id'
      path: '/purchase-return/$id'
      fullPath: '/purchase-return/$id'
      preLoaderRoute: typeof PurchaseReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-return/new': {
      id: '/purchase-return/new'
      path: '/purchase-return/new'
      fullPath: '/purchase-return/new'
      preLoaderRoute: typeof PurchaseReturnNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof PurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id': {
      id: '/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof PurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/new': {
      id: '/purchase/new'
      path: '/purchase/new'
      fullPath: '/purchase/new'
      preLoaderRoute: typeof PurchaseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations_/$id': {
      id: '/quotations_/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof QuotationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-return/': {
      id: '/sale-return/'
      path: '/sale-return'
      fullPath: '/sale-return/'
      preLoaderRoute: typeof SaleReturnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-return/$id': {
      id: '/sale-return/$id'
      path: '/sale-return/$id'
      fullPath: '/sale-return/$id'
      preLoaderRoute: typeof SaleReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale-return/new': {
      id: '/sale-return/new'
      path: '/sale-return/new'
      fullPath: '/sale-return/new'
      preLoaderRoute: typeof SaleReturnNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/edit/$id': {
      id: '/purchase/edit/$id'
      path: '/purchase/edit/$id'
      fullPath: '/purchase/edit/$id'
      preLoaderRoute: typeof PurchaseEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/edit/$id': {
      id: '/sales/edit/$id'
      path: '/sales/edit/$id'
      fullPath: '/sales/edit/$id'
      preLoaderRoute: typeof SalesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  CashRoute: CashRoute,
  DaybookRoute: DaybookRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  GstRoute: GstRoute,
  InventoryRoute: InventoryRoute,
  ItemsRoute: ItemsRoute,
  JournalVouchersRoute: JournalVouchersRoute,
  LoginRoute: LoginRoute,
  PartiesRoute: PartiesRoute,
  PayeesRoute: PayeesRoute,
  PaymentsRoute: PaymentsRoute,
  ProformaRoute: ProformaRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  BankIdRoute: BankIdRoute,
  ItemsIdRoute: ItemsIdRoute,
  PartiesIdRoute: PartiesIdRoute,
  PayeesIdRoute: PayeesIdRoute,
  ProformaIdRoute: ProformaIdRoute,
  PurchaseReturnIdRoute: PurchaseReturnIdRoute,
  PurchaseReturnNewRoute: PurchaseReturnNewRoute,
  PurchaseIdRoute: PurchaseIdRoute,
  PurchaseNewRoute: PurchaseNewRoute,
  QuotationsIdRoute: QuotationsIdRoute,
  SaleReturnIdRoute: SaleReturnIdRoute,
  SaleReturnNewRoute: SaleReturnNewRoute,
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  PurchaseReturnIndexRoute: PurchaseReturnIndexRoute,
  PurchaseIndexRoute: PurchaseIndexRoute,
  SaleReturnIndexRoute: SaleReturnIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  PurchaseEditIdRoute: PurchaseEditIdRoute,
  SalesEditIdRoute: SalesEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
